# Generated by Django 3.1.3 on 2020-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_vulnerability_affected_host'),
        ('hosts', '0002_auto_20201106_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host',
            field=models.ManyToManyField(to='vulnerabilities.Vulnerability'),
        ),
    ]
