# Generated by Django 3.1.3 on 2020-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0005_remove_vulnerability_affected_host'),
        ('hosts', '0003_host_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='book_list', to='vulnerabilities.Vulnerability'),
        ),
    ]
