# Generated by Django 3.1.3 on 2020-11-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_title', models.CharField(max_length=200)),
                ('vulnerability_severity', models.CharField(max_length=50)),
                ('vulnerability_cvss', models.FloatField()),
                ('vulnerability_publication_date', models.DateField()),
                ('vulnerability_fixed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
    ]
